- config.py
- siegen.py
Added a simple parser for Uni Siegen.
Prices and legend still missing, but main information is available.
> Added Uni Siegen

- .gitignore
- config.py
- erlangen_nuernberg.py
Hello,
I've created a parser so canteens belonging to "Studentenwerk Erlangen Nürnberg" get available via openmensa.org.
rgds Schabi
> add parser for canteen belonging to erlangen nuernber

- erlangen_nuernberg.py
Yet another pull request had to be done. Sorry for annoying you again. How can I test if openmensa.org will fail or not?
The following changes on erlangen_nuernberg where made:
* add support for "Tipp des Tages"
* made parser support dates in the formate "dd.mm"
> Fixed serveral issues

- erlangen_nuernberg.py
Some special tags which temporarily exist made the parser fail. So we need a proper exception handling to keep on parsing even if a small thing fails.
> add exception handling to erlangen_nuernberg

- README.md
Squashed the following:
* fixed wront markdown notation
* fixed wront markdown notation again
> add travis build state batch to readme

- erlangen_nuernberg.py
Sometimes it's spargeltag in germany.
Heil Spargeltage (not).
> add spargeltage

- erlangen_nuernberg.py
fixed parsing problem related to the "action tandem" tag on the erlangen langemark menu site.
> fixed action tandem parsing problem

- chemnitz_zwickau.py
The initial version had some issue with the price. These should be fixed now.
> chemnitz_zwickau: fix price parsing issue

- erlangen_nuernberg.py
The [erlangen nuernberg](http://www.werkswelt.de/) website has change dramatically. This crawler can handler the new website.
> innitial release for the new erlangen/nuernberg parser

- erlangen_nuernberg.py
- ostniedersachsen.py
> update erlangen nuernberg parser to use xml api

- muenchen.py
> WIP: Fix muenchen and nuernberg parser

- niederbayern_oberpfalz.py
> niederbayern-oberpfalz: Update legend

- config.py
- duesseldorf.py
- test-urls.txt
Parser for canteens operated by "Studentenwerk Düsseldorf". Food additive list is maintained as PDF and difficult to parse, hence a static dictionary compiled from that PDF is included with the parser.
> added parser for "Studentenwerk Düsseldorf"

- erlangen_nuernberg.py
- test-urls.txt
They changed things again. So I had to change things to :/
> fix recent changes to erl_nuernberg mensa

- muenchen.py
All tables were replaced with lists and definition lists. The additions are available again on the page for parsing. The prices are still on a separate page using the old markup.
> muenchen: rewrite parser for the new website markup

- erlangen_nuernberg.py
Before there was only one note string, but that violated xml standard. So now every foot ingredient is an own note.
> make notes a list for erl./nbg

- erlangen_nuernberg.py
fix nodes in erlangen nuernberg
> fix nodes in erlangen nuernberg

- erlangen_nuernberg.py
add sulfid allergen for erlangen/nuernberg
> add sulfid allergen for erlangen/nuernberg

- build_scripts/test-urls.txt
- config.py
- parsers/saarland.py
This PR adds support for the API provided by [mensaar.de](https://mensaar.de/) and thus for the following universities:
* Mensa / Mensacafe Saarbrücken
* Mensa Homburg
* Cafeteria HTW Göttelborn
Fixes #1
> Add parser for mensaar.de api

- parsers/dresden.py
New css class `swdd-link-list-item` for meals.
> Fix dresden parser

- build_scripts/test-urls.txt
- parsers/ostniedersachsen.py
- parsers/rostock.py
- parsers/wuerzburg.py
TODO:
* `campus` is just lueneburg now
* `rotes-feld` was closed in 2017 (?)
> WIP: Rewrite the ostniedersachsen parser based on the API

- parsers/erlangen_nuernberg.py
remove baernenschanze and hofeder as these mensas don't exist enymore
fix errors with new CO2 food category
> fix issues with erlangend nuremberg parser
